### ISSUE TITLE
an error using aimmy v2

### ISSUE THREAD

**Issue by joshclark756** [Babyhamsta/Aimmy#1361]
when i choose any model at all this shows up 
![image_2024-02-24_133258974](https://github.com/Babyhamsta/Aimmy/assets/89812074/3079ca0a-18bc-4b08-98f0-67d8d8671162)

**Comment by zoeywowy** [comment]
Try reinstalling the necessary programs to run aimmy!

**Comment by ccroic** [comment]
Try using 1.5.2, because v2 has many bugs with starting ONNX models and others.

**Comment by joshclark756** [comment]
i use 1.5.2 and it has worked perfectly for me

**Comment by Babyhamsta** [comment]
Please upgrade to 2.1.0, most of the bugs should be fixed.

**Comment by jesse-dimtl** [comment]
still facing the problem after upadating to the lastest version 2.1.5
![sfafc](https://github.com/user-attachments/assets/63abb05b-eede-4346-af05-be81b7be3de5)

**Comment by jesse-dimtl** [comment]
![Uploading fsafa.jpg…]()

**Comment by jesse-dimtl** [comment]
![fsafa](https://github.com/user-attachments/assets/67c54353-c909-48a9-91b3-e64261ef1c16)

**Comment by joshclark756** [comment]
> still facing the problem after upadating to the lastest version 2.1.5 ![sfafc](https://private-user-images.githubusercontent.com/185899605/378754357-63abb05b-eede-4346-af05-be81b7be3de5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTE4NzEsIm5iZiI6MTcyOTU5MTU3MSwicGF0aCI6Ii8xODU4OTk2MDUvMzc4NzU0MzU3LTYzYWJiMDViLWVlZGUtNDM0Ni1hZjA1LWJlODFiN2JlM2RlNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQxMDA2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTZmOWRhZjJjNGQ1MzZjYWM1NjQ3YTYzMDI2ZDIzNTE5OTJiZWRhOGJiOWYwMWJhM2UyZTcwNTI3YTczYTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gZARjSOPcF5TIOKuo0jrJybY9mDWw_8R3zM3HMtqIt4)

the problem with me was actually just my hardware so that might be the issue
